### ISSUE TITLE
Column label not always high enough

### ISSUE THREAD

**Issue by freaktechnik** [jeremypw/gnonograms#10]
The label content overflows its container, or at least the visible container.

![image](https://user-images.githubusercontent.com/640949/36634862-911dbc0e-19ab-11e8-9bc7-3bf8a15177d7.png)

**Comment by jeremypw** [comment]
Thanks for raising this.  It is relatively rare to get 7 clues for a region length 15, which is maybe I did not spot it.  Will be fixed in next release (probably a couple of weeks).

**Comment by jeremypw** [comment]
Should be fixed by 7e926be3ff9368866844802357e0dc827a7d24be.
In order to avoid wasting space, the labels are sized according to the maximum likely clue length, not the maximum possible clue length and in order to avoid the window size altering for each generated game the font-size is reduced on a per label basis if the text is too long.
