### ISSUE TITLE
Board size not restored

### ISSUE THREAD

**Issue by freaktechnik** [jeremypw/gnonograms#8]
Did the board size change with the latest update? The window and individual cells are suddenly much larger for me. Being able to scale the board would be really nice.

**Comment by jeremypw** [comment]
@freaktechnik I did not notice this but it could be a side-effect of another change.  The minimum window size is larger because there are more widgets in the header bar. You can scale the board using either `Ctrl-Scroll` or `Ctrl-minus`/`Ctrl-plus`  (`Ctrl-equal` works as `Ctrl-plus` as well).  The cell size (governed by the font-height) is saved in the settings on close and is supposed to be restored on reopening.  However, I have now noticed that there is a regression that is causing the the font-height to be recalculated every time the app is opened to give a large window that will fit onto the screen (this is only supposed to happen when you change the board-size).

I will edit the title of this issue slightly and issue a fix in the next release. 

Thanks for letting me know :-)

**Comment by freaktechnik** [comment]
Thank you, I did not know about <kbd>Ctrl</kbd> + Scroll Wheel resp. <kbd>+</kbd>/<kbd>-</kbd> zooming.

**Comment by jeremypw** [comment]
I am working on a document in the wiki that lists all the controls and shortcuts.

**Comment by jeremypw** [comment]
This should be fixed by 73f8ece411b2d138ade2d24334affbdddca6bbfb.
